### PR TITLE
feat: tuning 50-59/60 pvp sets

### PR DESCRIPTION
**Pull request by Helias**
I increased the request honor price of 10k in these vendors:
- https://wowgaming.altervista.org/aowow/?npc=12785 (alliance)
- https://wowgaming.altervista.org/aowow/?npc=12795 (horde)
- https://wowgaming.altervista.org/aowow/?npc=15127 (alliance)
- https://wowgaming.altervista.org/aowow/?npc=15126 (horde)

This will improve the experience during the Classic PvP progression.

### CODE REVIEW

**Comment by locus313** [comment]
@Helias why separating it into tuning? Shouldn't we just make it part of the progression?

**Comment by Helias** [comment]
Nice question, actually I am not sure if adding the `tuning` directory or not.
I added it because these values are "custom", are not related to Classic or TBC or WoTLK **blizzlike behavior**, I increase to 10k honor arbitrarily, so if someone wants to keep the progression as blizzlike as possible, they should not use the tuning I think.

What do you think?

**Comment by 55Honey** [comment]
I think every kind of progression is a tiny bit custom. I agree with Locus, adding it to the progression makes sense. People can still decide if they add that specific file later.

**Comment by Helias** [comment]
updated, discussing with @JamesGent I made new prices for 50-59 and I created two phases:
- 50-59 starting phase
- 50-59 end phase, this is still a work in progress, I need to enable some NPCs to sell the lieutenant items (lvl 58 with high item lvl) and increase a bit their req honor price https://wotlk.evowow.com/?search=Lieutenant+Commander%27s+#items

We should enable the 50-59 end phase after that we open all PvE contents

**Pull request merged**
